import {
  engine,
  type MapComponentDefinition,
  Material,
  MaterialTransparencyMode,
  type PBMaterial_PbrMaterial,
  Schemas
} from '@dcl/sdk/ecs'

import { Color4 } from '@dcl/sdk/math'
import { syncEntity } from '@dcl/sdk/network'
import { SyncEntityEnumId } from '../syncEntities'

export const customizationEntity = engine.addEntity()

export const CustomizationState = engine.defineComponent('customizationState', {
  accentColor: Schemas.Color4,
  textureSrc: Schemas.String
})
CustomizationState.create(customizationEntity, {
  accentColor: Color4.Black(),
  textureSrc:
    'https://github.com/Fanny-Pack-Studios/decentraland-teamhub/blob/main/assets/images/autogenerated-thumbnail.png?raw=true'
})

type CustomizationStateType = typeof CustomizationState extends MapComponentDefinition<infer Inner> ? Inner : never

export function getMutableCustomizationState(): CustomizationStateType {
  return CustomizationState.getMutable(customizationEntity)
}

CustomizationState.onChange(customizationEntity, (component) => {
  console.log(component)
  for (const bannerName of ['BannerLogo', 'BannerLogo_2', 'Logo']) {
    const entity = engine.getEntityOrNullByName(bannerName)
    if (entity !== null) {
      const texture = Material.Texture.Common({
        src: component?.textureSrc ?? ''
      })
      Material.setBasicMaterial(entity, {
        texture
      })
    }
  }

  const accentMaterialParams: PBMaterial_PbrMaterial = {
    albedoColor: component?.accentColor ?? Color4.Black(),
    // texture: Material.Texture.Common({
    //     src: "", TODO: Add texture
    // }),
    transparencyMode: MaterialTransparencyMode.MTM_ALPHA_BLEND
  }

  for (const bannerName of ['Accent', 'BannerBackground', 'BannerBackground_2']) {
    const entity = engine.getEntityOrNullByName(bannerName)
    if (entity !== null) {
      Material.setPbrMaterial(entity, accentMaterialParams)
    }
  }
})

export function setupCustomization(): void {
  syncEntity(customizationEntity, [CustomizationState.componentId], SyncEntityEnumId.CUSTOMIZATION_STATE)
}
